sudo: required
services:
    - docker
    
before_install:
    - docker build -t  ahmadshekha/docker-react -f Dockerfile.dev .

script:
    - docker run ahmadshekha/docker-react npm run test -- --coverage
    
    